### ISSUE TITLE
Creare due branch separati

### ISSUE THREAD

**Issue by jkomyno** [FIUP/Programmazione_1#1]
L'idea è quella di separare gli esercizi del primo compitino da quelli del secondo in due branch distinti. Fatemi sapere cosa ne pensate.

**Comment by sydernee** [comment]
A che pro creare un branch per ogni compitino? IMHO si abuserebbe del branching quando in realtà basterebbe creare due cartelle, non ne vedo l'utilità.

Io piuttosto adotterei una variante semplificata di [questo modello di branching model](http://nvie.com/posts/a-successful-git-branching-model/).

**Comment by Archetipo95** [comment]
Che signica separere gli esercizi del primo/secondo compitino? Questi sono tutti gli es assegnati da filé e sono divisi per anno
